I want to run the following experiment,
Where I want to store the counts in an array that I print later. If I run it for one point it's fine, for more than one point I get,
I get the following error,
I get the same error if I have, self.core.break.real_time()
With error message,
How should I run this experiment, then?
Maybe unrelated but trying to measure how long this step takes,
self.results[i] = self.detect(ct)
using time.time gives me a value of about 3.5s. That seems a little long to me. Is that normal?
As demonstrated by:
Another odd problem is the second compilation of k is not rejected in my example.
The second compilation is not rejected because the embedding code does the equivalent of guessing the width for int literals when typechecking. No mystery here.
Would this fix be in 1.0rc3 ? I'm running the following experiment on windows and linux,
If self.points = 1, it's fine, if self.points=2 I get this error,
The fix is not in 1.0rc3.
